### ISSUE TITLE
POST requests over HTTPS fail with 403 "Invalid CORS request"

### ISSUE THREAD

**Issue by hyunh90** [EtienneLamoureux/sc-trade-tools#10]
Site functionality is completely broken with below error:
![image](https://user-images.githubusercontent.com/1912333/86501592-42039180-bd68-11ea-9753-2ef74fc97982.png)

### Environment
* Firefox 77.0.1
* Enhanced tracking protection is OFF for the site
* uBlock Origin is OFF for the site
* Privacy Badger is OFF for the site

### Steps to reproduce
* Access [Best buyer](https://sc-trade.tools/best-buyer) (note: this breakage happens all three functions)
* Find any commodity and enter any amount
* Click on Submit

### Expected output
The tool lists potential best buyers.

### Actual output
The tool fails to load with aforementioned error.

**Comment by EtienneLamoureux** [comment]
Thank you for the detailed report.

Can you reproduce the issue when using the [Mirror](http://3.128.227.240/)?

This error message is consistent with an impossibility to reach the server, which I expect to happen in the early days of DNS propagation. It's only been ~18h since the last name servers change, so one call might reach and the next fail.

**Comment by EtienneLamoureux** [comment]
I'll turn off SSL temporarily while I resolve this issue.

**Comment by hyunh90** [comment]
Yup, on the mirror it works just fine.

**Comment by EtienneLamoureux** [comment]
Tests
- On the origin server directly: works
- Through cloudflare over HTTP: works
- Through cloudflare over HTTPS: 403 "Invalid CORS request"

**Comment by EtienneLamoureux** [comment]
The joys of CORS. Should be all good now.
