### ISSUE TITLE
Fix missing commodity: SLAM

### ISSUE THREAD

**Issue by oblair** [EtienneLamoureux/sc-trade-tools#107]
Slam is missing.
This is the most lucrative commodity for sale at the moment.
Buying at Jumptown, Private Property and The Orphanage.
Selling at Orinth.

**Comment by EtienneLamoureux** [comment]
Thanks for the report.

The problem is that, even if they added some sell points to the commodity, those new sell points are not present in the raw data. I'll check again once [3.12.0r PTU.6787151](https://robertsspaceindustries.com/spectrum/community/SC/forum/190048/thread/star-citizen-alpha-3-12-0r-ptu-6787151-patch-notes) goes live.
