### ISSUE TITLE
Laramite production on Wala (3.16)

### ISSUE THREAD

**Issue by rodillacero** [EtienneLamoureux/sc-trade-tools#114]
Hello,

The price of Laramite is around 27 in Wala ( Arcop Mining 45), not 25.

The production of Laramite seems not be 2000/min but around 1000/min.

thanks !

Rodi

**Comment by EtienneLamoureux** [comment]
Hi and thanks for the question.

Prices will vary from what the website say due to the dynamic supply and demand.

Apparent refresh rates will also seem lower than advertised because they are shared between all the servers: your particular server may not get the full refresh is multiple instances of the shop are being traded with at the moment, which is often the case with Laranite!

For more info, feel free to check https://sc-trade.tools/home#faq

**Comment by rodillacero** [comment]
Ok thanks Etienne, i not understood the global economy of SC.  sorry for this

**Comment by EtienneLamoureux** [comment]
No worries! It's not explained in-game at all :D
