### ISSUE TITLE
Are inventories & refresh rates accurate?

### ISSUE THREAD

**Issue by teddwyer** [EtienneLamoureux/sc-trade-tools#44]
has 3.10 has completely revamped the stock information at each site? for example, I landed at Shubin Mining Facility SM0-22 on Microtech and there were only 9349 units of Astatine a tick... the amount available seems to be variable across time... if you are willing to wait long enough then there will a random amount available...a little annoying... not sure if the stock continues to build or if it is only available for whatever the last amount was...

**Comment by EtienneLamoureux** [comment]
Hi and thanks for the feedback! As I try to make SC Trade Tools as useful as possible, I do acknowledge that not everything is crystal clear yet, so questions/reports like these are very helpful.

You can see my answer to a similar question [here](https://github.com/EtienneLamoureux/sc-trade-tools/issues/43#issuecomment-671329001), but the gist is that inventories and refresh rates are shared across all servers. So if someone if buying the same commodity as you are on another server, you'll see that much less stock where you are. I'll try to add a note to make that more obvious, but since CIG doesn't have APIs for us to hook into and read real-time stock information, we can only display the static data from the game's files.

https://github.com/EtienneLamoureux/sc-trade-tools/issues/37
