### ISSUE TITLE
Don't display refinery terminals in trade results

### ISSUE THREAD

**Issue by Kjasi** [EtienneLamoureux/sc-trade-tools#78]
## Describe the bug
Mining resources are being listed as tradable to trading terminals, and Trading resources are being listed as tradable to refinery terminals.

## To Reproduce
1. Search for a commodity with the same name as a mining resource, such as Agricium.
1. See Refinery Terminals listed in the "bought by" list, alongside normal trading posts.

## Expected behaviour
Only refinery terminals should be able to buy Agricium, the minable ore (and other minable ores), while Agricium, the trading resource, should only be sold to trading terminals.

The simplest solution (from the user's end) would be to have 2 listings for overlapping names, so Agricium the trading resource isn't linked to Agricium the mining resource, as the mining resource cannot be sold to trade terminals, nor can the trading resource be sold to refinery terminals.

I recommend that resources that are mined could be separated by having (Ore) appended to their names, to help keep their listings separate. Additionally, (Cargo) could be appended to the trading resource, when these names overlap.

**Comment by EtienneLamoureux** [comment]
Thanks for the report, I'll start thinking about a solution.

Interestingly enough, this happens because the minable and the cargo variants of a commodity are actually not variants: they are the exact same thing! It's as if the refinery terminal can only be sold to from a mining ship and the normal trading terminal can only be interacted with by anything but a mining ship.
