### ISSUE TITLE
En route contains empty cargo entries in search result

### ISSUE THREAD

**Issue by SerethiX** [EtienneLamoureux/sc-trade-tools#95]
## Describe the bug

On some routes the possible trading routes produce detours that are not useful at all, like `detour to X > buy nothing > detour to Y > sell nothing > continue to your destination`

## To Reproduce
Ship: Caterpillar
Initial investment: 200.000
Origin: Port Olisar
Destination: Lorville > Central Business District
Maximum number of stops: 5

## Expected behaviour
Get routes that yield at least a little money and not waste time 😏 

## Screenshots
![grafik](https://user-images.githubusercontent.com/3373740/102009687-6ca33e80-3d39-11eb-88a7-27bc5a97b421.png)

**Comment by EtienneLamoureux** [comment]
Hi and thanks for the report!

This is actually a feature: sometimes the best route in a multi-stop itinerary has an empty leg. This is mostly due to the fact that outposts have very limited buy/sell options, so once in a while you have to hop to another one to maximize your overall profit. For now, such empty travels are limited to the same planet/moon.

In this particular case, there's probably not much to carry between Grim Hex and Loreville's CBD, so a quick detour for the very profitable Astatine makes sense. And [Benson](https://sc-trade.tools/shops/Stanton%20%3E%20Crusader%20%3E%20Yela%20%3E%20Benson%20Mining%20Outpost) doesn't accept anything that [Grim Hex](https://sc-trade.tools/shops/Stanton%20%3E%20Crusader%20%3E%20Yela%20%3E%20Grim%20HEX%20%3E%20Admin) sells.

It's all calculated though: if the algorithm says an empty travel is optimal, it is!
